# Generated by Django 5.1.5 on 2025-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
        migrations.AddField(
            model_name='customuser',
            name='solax_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
