# Generated by Django 5.1.5 on 2025-05-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_communitypost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='energy_usage',
        ),
    ]
